apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-green
  namespace: capstone
  labels:
    app: capstone-green
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: capstone-green
  template:
    metadata:
      labels:
        app: capstone-green
    spec:
      containers:
        - name: capstone-green
          image: 813213957333.dkr.ecr.us-west-2.amazonaws.com/capstone:latest
          ports:
            - containerPort: 8080
      nodeSelector:
        deploy: green
